<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <RuntimeIdentifier>android-arm</RuntimeIdentifier>
    <SupportedOSPlatformVersion>23.0</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <RootNamespace>ClipRemote.Mobile</RootNamespace>
    <ApplicationTitle>ClipRemote</ApplicationTitle>
    <ApplicationId>com.treska23.clipremote</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>0.1</ApplicationDisplayVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
